services:
  backend-test:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    command: npm run test 

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run test 