name: Assessify CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  testing-phase:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v5

    - name: Run Docker Compose Automation Tests
      run: |
        docker compose -f docker-compose.test.yml up --build --abort-on-container-exit

    - name: Clean up Test Containers
      run: docker compose -f docker-compose.test.yml down


  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy.sarif

  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Semgrep
        run: pip install semgrep

      - run: semgrep ci --sarif --output semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        continue-on-error: true

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2 # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}

  osv-scanner:
    needs: testing-phase
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.8"

  workflow-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - uses: zizmorcore/zizmor-action@v0.5.6
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif
          category: zizmor

